/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 scene.gltf 
Author: 2143087 (https://sketchfab.com/2143087)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/astronot-466c8ae385854dda99a2dc2bc2ac5c58
Title: Astronot
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[0.005, 0.006, 0]} scale={0.001}>
        <mesh geometry={nodes.Object_6.geometry} material={materials.material} position={[-0.009, -256.03, 246.313]} scale={2.524} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.material_1} position={[-0.009, -256.03, 246.313]} scale={2.524} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
